### ISSUE TITLE
license

### ISSUE THREAD

**Issue by igorbarinov** [RCasatta/op_return#3]
What is your the license for your code? I'd like to put it on my website about bitcoin analytics

**Comment by RCasatta** [comment]
Hi, consider it MIT license

**Comment by RCasatta** [comment]
What is you site by the way?

**Comment by igorbarinov** [comment]
ok, thanks.
my project is http://www.blocknotary.com/
for the https://itunes.apple.com/us/app/blocknotary-proof-existence/id998052799?mt=8 app

it doesn't contain analytics .. yet)
