### ISSUE TITLE
blockchain ID transactions displayed as sub-categories 

### ISSUE THREAD

**Issue by muneeb-ali** [RCasatta/op_return#4]
It looks like in http://opreturn-976.appspot.com/ the different name operations for blockchain ID are being categorized as different protocols. id+, id>, id: etc are all blockchain ID transactions and should all be displayed under the single "blockchain ID" category. Let me know if you need any further details and keep up the great work!

**Comment by RCasatta** [comment]
They are grouped under the same protocol now. 79cc8f19cbc3056d9dd751d46754cddbacb58d10
