### ISSUE TITLE
better way of displaying non-printable ascii characters

### ISSUE THREAD

**Issue by shea256** [RCasatta/op_return#8]
As far as I can tell, the question mark shown in the graphs is a stand-in for non-printable ascii characters.

Can we update this so that instead of showing a question mark the binary code for the character is shown? This could be something like `\x1E`.

**Comment by RCasatta** [comment]
Now recognizing non printable character and displaying hex value with suffix `0x`

**Comment by shea256** [comment]
Awesome! Looks great.
